name: Perpetual VDS with tmate

on:
  # Позволяет запускать вручную из интерфейса GitHub
  workflow_dispatch:

  # Позволяет воркеру запускать самого себя для перезапуска
  repository_dispatch:
    types: [restart-vds]

jobs:
  build:
    runs-on: ubuntu-latest
    # Таймаут 5 часов 55 минут, чтобы оставить 5 минут на бэкап и перезапуск
    timeout-minutes: 355

    steps:
      # Шаг 1: Скачиваем код репозитория
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 2: Восстанавливаем данные из бэкапа, если он существует
      - name: Restore Data from Backup
        run: |
          if [ -f "vds_backup.zip" ]; then
            echo "Backup file found. Restoring..."
            # Распаковываем архив с заменой существующих файлов
            unzip -o vds_backup.zip -d ./
            # Убедитесь, что конфигурационный файл x-ui.db восстановлен!
          else
            echo "No backup found. Starting fresh."
          fi

      # НОВЫЙ ШАГ (A): Устанавливаем необходимые пакеты
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y curl unzip

      # НОВЫЙ ШАГ (B): Устанавливаем 3X-UI
      - name: Install and Start 3X-UI
        run: |
          echo "Installing 3X-UI..."
          # Выполняем скрипт установки 3X-UI
          bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) <<EOF
n # Отвечаем 'n', чтобы не настраивать порт вручную (или 'y' и указываем порт, но это усложнит)
admin # Имя пользователя по умолчанию (измените)
password # Пароль по умолчанию (измените)
EOF
          # После установки панель должна автоматически запуститься. 
          # Если нет, вы можете попробовать запустить ее вручную.
          # Если вы указали порт 8080 при ручной установке, используйте:
          # systemctl start x-ui 
          
          # Так как tmate будет запущен в следующем шаге, он сохранит сессию.

      # Шаг 3 (был 3): Устанавливаем tmate и запускаем сессию в фоне
      - name: Setup and Run tmate
        id: tmate_session # Даем ID шагу, чтобы получить его вывод в следующих шагах
        run: |
          sudo apt-get install -y tmate # Установка уже в Шаге (A)
   
          # Запускаем tmate в фоновом режиме (в "детаче")
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
   
          # Получаем SSH-строку и передаем ее как вывод шага
          TMATE_SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "TMATE_SSH_URL=${TMATE_SSH}" >> $GITHUB_OUTPUT
          echo "========================================================================="
          echo "SSH connection string: ${TMATE_SSH}"
          echo "========================================================================="
   
      # Шаг 4: Сохраняем SSH-ссылку в текстовый файл для удобства
      - name: Save SSH Link to File
        run: echo "${{ steps.tmate_session.outputs.TMATE_SSH_URL }}" > ssh_link.txt
 
      # Шаг 5: ОСНОВНОЙ РАБОЧИЙ ЦИКЛ. Здесь сервер "живет"
      - name: Keep VDS Alive
        run: |
          echo "VDS is running. Will shut down and backup in approximately 5 hours 45 minutes."
          # Ждем ~5ч 45м (20700 секунд). Оставляем 10 минут на бэкап и перезапуск.
          sleep 20700

      # Шаг 6: Создаем бэкап ПЕРЕД выключением
      - name: Create Backup
        run: |
          echo "Creating data backup..."
          # Важно: Скрипт 3X-UI может сохранять данные в разных местах, но обычно это /etc/x-ui/x-ui.db
          # На всякий случай, архивируем все, что есть, чтобы не потерять базу данных панели.
          zip -r vds_backup.zip . -x ".git/*" "vds_backup.zip" "ssh_link.txt"

      # Шаг 7: Сохраняем бэкап и SSH-ссылку в репозиторий
      - name: Commit Backup and SSH Link
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "VDS Backup & SSH Link Auto-Update"
          file_pattern: "vds_backup.zip ssh_link.txt"

      # Шаг 8: Запускаем следующую сессию (АВТОРЕСТАРТ)
      - name: Trigger Next VDS Run
        run: |
          echo "Triggering VDS restart..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "restart-vds"}'
